# Generated by Django 5.0 on 2024-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='secondname',
            field=models.CharField(max_length=64),
        ),
    ]
